spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/server_manager_db
    username: postgres
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # Choose: validate,update,create. create - useful in development level, creating tables on every startup
    show-sql: true # Turn on/off SQL query in console - useful in development mode
  database-platform: org.hibernate.dialect.PostgreSQLDialect
